language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
install:
  - gem install pdd -v 0.20.5
  - gem install xcop -v 0.6
  - gem install est -v 0.3.4
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
script:
  - set -e
  - mvn clean install --errors --batch-mode
  - mvn clean
  - pdd -f /dev/null
  - est --dir=est --file=/dev/null
jdk:
  - oraclejdk11
